import type { CoverageDistrictProfile } from "@/lib/seo/coverage-district-types";

/** أحياء 26–50 */
export const PROFILES_PART_B: CoverageDistrictProfile[] = [
  {
    slug: "al-balad",
    archetype: "historic",
    character:
      "حي البلد قلب جدة التاريخي؛ مباني عمرها عقود وشبكات مواسير من النحاس والحديد القديم. التسربات الخفية شائعة مع فواتير مرتفعة. الكشف بدون تكسير واسع ضروري لحماية البلاط والجدران التراثية.",
    buildingTypes: ["مباني تراثية", "عمائر قديمة", "محلات تقليدية"],
    issues: [
      { title: "مواسير نحاس قديمة", detail: "تآكل الوصلات يسبب تسربًا بطيئًا تحت الأرضيات." },
      { title: "تسرب خفي دون بقع", detail: "الفاتورة ترتفع قبل ظهور رطوبة." },
      { title: "خزانات أرضية قديمة", detail: "تشققات في الخرسانة." },
      { title: "تجديد دون كشف", detail: "تركيب بلاط جديد فوق تسرب قائم." },
    ],
    inspectionPriorities: [
      "تقييم نوع المواسير والعمر.",
      "فحص حراري قبل أي تكسير.",
      "خزان أرضي إن وُجد.",
      "تقرير للترميم أو البيع.",
    ],
    insulationFocus: "عزل حراري ومائي بحذر في البلد — مواد تتوافق مع طبيعة المبنى القديم.",
    seasonalNote: "قبل ترميم البلد — كشف وتوثيق إلزامي.",
    scenarios: [
      { title: "مبنى تراثي", body: "تسرب من نحاس — استبدال جزء بأقل ضرر." },
      { title: "فاتورة", body: "تسرب خفي — كشف حراري." },
    ],
    tips: [
      "كشف قبل أي ترميم.",
      "لا تكسير عشوائي.",
      "توثيق للتراث.",
      "استبدال النحاس التالف.",
      "تقرير فاتورة.",
      "عزل عند التجديد الكامل.",
    ],
    extraFaqs: [
      { question: "هل تتعاملون مع مباني تراثية في البلد؟", answer: "نعم، بأقل تدخل ممكن." },
      { question: "مواسير نحاس؟", answer: "نفحصها ونوصي بالاستبدال عند التآكل." },
    ],
    neighbors: ["al-baghdadiyah-al-sharqiyah", "al-kandarah", "al-ruwais", "ghulail"],
  },
  {
    slug: "al-baghdadiyah-al-sharqiyah",
    archetype: "historic",
    character:
      "البغدادية الشرقية من أحياء وسط جدة القديمة؛ عمائر كثيفة وشبكات متداخلة. التسربات بين الشقق والمحلات شائعة. يحتاج تنسيقًا بين السكان والتجار.",
    buildingTypes: ["عمائر قديمة", "شقق", "محلات"],
    issues: [
      { title: "خط مشترك", detail: "سكني وتجاري." },
      { title: "شبكة قديمة", detail: "تآكل." },
      { title: "رطوبة جدار", detail: "بين وحدات." },
      { title: "خزان علوي", detail: "صيانة ناقصة." },
    ],
    inspectionPriorities: [
      "تحديد مسار الشبكة.",
      "فحص تجاري وسكني.",
      "تنسيق أطراف.",
      "تقرير موضوعي.",
    ],
    insulationFocus: "عزل حمامات عند الترميم في البغدادية الشرقية.",
    seasonalNote: "الكثافة تتطلب تدخلًا سريعًا.",
    scenarios: [
      { title: "محل وشقة", body: "خط مشترك — إصلاح موضعي." },
      { title: "عمارة", body: "خزان علوي." },
    ],
    tips: [
      "تنسيق مع الجيران.",
      "كشف قبل الترميم.",
      "تقرير للعمارة.",
      "فحص الخزان.",
      "لا إصلاح دون مصدر.",
      "توثيق بالصور.",
    ],
    extraFaqs: [
      { question: "محلات في البغدادية الشرقية؟", answer: "نعم." },
      { question: "عمارات قديمة؟", answer: "خبرة في الشبكات المتداخلة." },
    ],
    neighbors: ["al-balad", "al-baghdadiyah-al-gharbiya", "al-kandarah", "al-ruwais"],
  },
  {
    slug: "al-baghdadiyah-al-gharbiya",
    archetype: "historic",
    character:
      "البغدادية الغربية حي قديم كثيف؛ شقق ومحلات بشبكات بحاجة صيانة دورية. ارتفاع الفاتورة والرطوبة في البدروم من الشكاوى المتكررة.",
    buildingTypes: ["عمائر", "شقق", "محلات"],
    issues: [
      { title: "بدروم رطب", detail: "تسرب أو صرف." },
      { title: "فاتورة", detail: "خط رئيسي." },
      { title: "حمام قديم", detail: "وصلات." },
      { title: "خزان", detail: "تشقق." },
    ],
    inspectionPriorities: [
      "بدروم أولًا.",
      "خط رئيسي.",
      "حمامات.",
      "خزان.",
    ],
    insulationFocus: "عزل وإصلاح حسب التشخيص — لا معالجة سطحية للبدروم.",
    seasonalNote: "أمطار تزيد رطوبة البدروم.",
    scenarios: [
      { title: "بدروم", body: "ماء من خط — ليس من الأمطار فقط." },
      { title: "فاتورة عمارة", body: "خط رئيسي." },
    ],
    tips: [
      "فحص بدروم سنوي.",
      "تنظيف مصارف.",
      "تنسيق عمارة.",
      "كشف مبكر.",
      "تقرير فاتورة.",
      "عزل عند الترميم.",
    ],
    extraFaqs: [
      { question: "رطوبة بدروم؟", answer: "نميّز بين تسرب مياه وصرف." },
      { question: "غربية vs شرقية؟", answer: "لكل حي صفحة ومحتوى مستقل." },
    ],
    neighbors: ["al-baghdadiyah-al-sharqiyah", "al-balad", "al-hindawiyah", "al-kandarah"],
  },
  {
    slug: "al-ruwais-al-jadid",
    archetype: "suburban-new",
    character:
      "الرويس الجديد يختلف عن الرويس القديم؛ عمائر وشقق أحدث نسبيًا. طلبات عزل عند الاستلام وكشف بعد تجديد الحمامات.",
    buildingTypes: ["عمائر حديثة", "شقق", "مجمعات"],
    issues: [
      { title: "عزل ناقص", detail: "سطح جديد." },
      { title: "بعد تجديد", detail: "تسرب وصلة." },
      { title: "خزان", detail: "تشقق نادر." },
      { title: "فاتورة", detail: "استهلاك." },
    ],
    inspectionPriorities: [
      "فحص عزل السطح.",
      "اختبار ضغط بعد سباكة.",
      "خزان.",
      "تقرير استلام.",
    ],
    insulationFocus: "فوم للأسطح الجديدة في الرويس الجديد.",
    seasonalNote: "فحص عند الاستلام من المطور.",
    scenarios: [
      { title: "شقة جديدة", body: "عزل ناقص — تقرير." },
      { title: "حمام مجدد", body: "وصلة — إصلاح." },
    ],
    tips: [
      "فحص استلام.",
      "اختبار ضغط.",
      "عزل فوم.",
      "توثيق ضمان.",
      "كشف سنوي.",
      "لا تخلط مع الرويس القديم.",
    ],
    extraFaqs: [
      { question: "الفرق عن حي الرويس القديم؟", answer: "مبانٍ أحدث — منهج فحص مختلف." },
      { question: "استلام من مطور؟", answer: "فحص شامل متاح." },
    ],
    neighbors: ["al-ruwais", "al-andalus", "al-balad", "al-jamaa"],
  },
  {
    slug: "al-hindawiyah",
    archetype: "historic",
    character:
      "الهنداوية حي قديم جنوب وسط جدة؛ عمائر كثيفة وشبكات قديمة. التسربات الخفية والفواتير المرتفعة تحتاج كشفًا منهجيًا.",
    buildingTypes: ["عمائر قديمة", "شقق", "محلات"],
    issues: [
      { title: "شبكة قديمة", detail: "تآكل." },
      { title: "تسرب خفي", detail: "جدار." },
      { title: "خزان", detail: "صيانة." },
      { title: "فاتورة", detail: "عمارة." },
    ],
    inspectionPriorities: [
      "تقييم الشبكة.",
      "فحص حراري.",
      "خزان.",
      "تقرير.",
    ],
    insulationFocus: "إصلاح ثم عزل عند الترميم في الهنداوية.",
    seasonalNote: "قبل ترميم — كشف.",
    scenarios: [
      { title: "تسرب خفي", body: "كشف حراري." },
      { title: "عمارة", body: "خط رئيسي." },
    ],
    tips: [
      "كشف قبل الترميم.",
      "فحص حراري.",
      "تقرير فاتورة.",
      "صيانة خزان.",
      "تنسيق عمارة.",
      "استبدال عند التآكل.",
    ],
    extraFaqs: [
      { question: "مباني قديمة الهنداوية؟", answer: "نعم." },
      { question: "تقرير فاتورة؟", answer: "متاح." },
    ],
    neighbors: ["al-baghdadiyah-al-gharbiya", "ghulail", "al-thaalbah", "al-kandarah"],
  },
  {
    slug: "al-kandarah",
    archetype: "historic",
    character:
      "الكندرة من أحياء جدة التاريخية الجنوبية؛ مباني قديمة وضيقة الشوارع. الكشف بدون تكسير واسع أولوية. تسربات الخزانات الأرضية شائعة.",
    buildingTypes: ["مباني قديمة", "شقق", "محلات"],
    issues: [
      { title: "خزان أرضي", detail: "تشقق." },
      { title: "مواسير قديمة", detail: "تآكل." },
      { title: "تسرب خفي", detail: "فاتورة." },
      { title: "ترميم", detail: "بدون كشف." },
    ],
    inspectionPriorities: [
      "خزان أرضي.",
      "فحص حراري.",
      "تقييم مواسير.",
      "أقل تكسير.",
    ],
    insulationFocus: "إيبوكسي للخزانات الأرضية في الكندرة عند الحاجة.",
    seasonalNote: "قبل ترميم — توثيق.",
    scenarios: [
      { title: "خزان أرضي", body: "إيبوكسي — توقف التسرب." },
      { title: "ترميم", body: "كشف قبل البلاط." },
    ],
    tips: [
      "فحص خزان أرضي.",
      "كشف قبل ترميم.",
      "لا تكسير عشوائي.",
      "تقرير فاتورة.",
      "إيبوكسي عند التشقق.",
      "توثيق تراثي.",
    ],
    extraFaqs: [
      { question: "خزانات أرضية الكندرة؟", answer: "نعم، فحص وإيبوكسي." },
      { question: "شوارع ضيقة؟", answer: "ننسق الموعد مسبقًا." },
    ],
    neighbors: ["al-balad", "al-thaalbah", "ghulail", "al-hindawiyah"],
  },
  {
    slug: "al-thaalbah",
    archetype: "historic",
    character:
      "حي الثعالبة جنوب قديم؛ عمائر وشقق بكثافة عالية وشبكات متقادمة. التسربات بين الطوابق والفواتير المرتفعة من أكثر البلاغات.",
    buildingTypes: ["عمائر كثيفة", "شقق", "محلات"],
    issues: [
      { title: "بين طوابق", detail: "حمام علوي." },
      { title: "خط مشترك", detail: "عمارة." },
      { title: "خزان", detail: "قديم." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "حمام علوي.",
      "خط عمارة.",
      "خزان.",
      "تقرير.",
    ],
    insulationFocus: "عزل حمام عند إعادة السيراميك في الثعالبة.",
    seasonalNote: "تدخل سريع — الكثافة.",
    scenarios: [
      { title: "بين طوابق", body: "حمام علوي." },
      { title: "عمارة", body: "خط مشترك." },
    ],
    tips: [
      "تواصل مع العلوي.",
      "تنسيق عمارة.",
      "كشف مبكر.",
      "عزل عند التجديد.",
      "تقرير فاتورة.",
      "فحص خزان.",
    ],
    extraFaqs: [
      { question: "كثافة الثعالبة؟", answer: "ننسق مع إدارة العمارة." },
      { question: "تسرب جار؟", answer: "فحص موضوعي." },
    ],
    neighbors: ["al-kandarah", "ghulail", "al-hindawiyah", "al-nuzlah-al-yamaniyah"],
  },
  {
    slug: "al-jamaa",
    archetype: "central-urban",
    character:
      "حي الجامعة من أحياء شمال وسط جدة النشطة؛ قربه من الجامعة والطرق الرئيسية يعني مزيجًا من شقق طلابية وعائلات وفلل صغيرة. التسربات في الحمامات المشتركة بالعمائر وخزانات الأسطح بعد الأمطار من أكثر طلبات السكان.",
    buildingTypes: ["عمائر سكنية", "شقق مؤجرة", "فلل صغيرة"],
    issues: [
      { title: "حمامات متعددة بالعمارة", detail: "صعوبة تحديد الشقة المسببة دون فحص منهجي لكل دور." },
      { title: "خزان علوي غير صيانة", detail: "تشققات دقيقة ترفع فاتورة العمارة كاملة أحيانًا." },
      { title: "تسرب بعد إصلاح سباكة رخيص", detail: "وصلات غير محكمة تحت البلاط." },
      { title: "ضعف ضغط مع استهلاك عالٍ", detail: "قد يدل على تسرب في خط التغذية الرئيسي." },
    ],
    inspectionPriorities: [
      "مراجعة شكاوى العمارة والعداد الرئيسي.",
      "فحص حراري لحمامات الأدوار العليا أولًا.",
      "اختبار ضغط على خط التغذية.",
      "تقرير يمكن تقديمه لإدارة العمارة.",
    ],
    insulationFocus:
      "في الجامعة ننصح بعزل حمامات بالفوم عند أي تجديد، وبيتومين أو فوم للأسطح المتوسطة حسب العمر — المعاينة تحدد.",
    seasonalNote: "مواسم الأمطار تزيد تسربات أسطح العمائر قرب الجامعة — فحص قبل نوفمبر.",
    scenarios: [
      { title: "عمارة 8 شقق — فاتورة جماعية", body: "الكشف حدد تسربًا من خزان الدور السابع؛ إصلاح موضعي دون تكسير كل الشقق." },
      { title: "شقة مؤجرة — رطوبة حمام", body: "وصلة دش قديمة — استبدال وعزل موضعي في زيارة واحدة." },
    ],
    tips: [
      "اختبار ضغط بعد أي سباكة في الشقة.",
      "تنسيق مع إدارة العمارة عند فاتورة مشتركة.",
      "فحص الخزان العلوي كل 6 أشهر في العمائر.",
      "عدم تجاهل رطوبة سقف الحمام.",
      "طلب كشف قبل تجديد عقد الإيجار.",
      "استخدام المشخّص الذكي لتقليل وقت الزيارة.",
    ],
    extraFaqs: [
      { question: "هل تخدمون عمائر قرب جامعة جدة في حي الجامعة؟", answer: "نعم، مع فحص للخطوط المشتركة والخزانات العلوية." },
      { question: "كم مدة كشف شقة في الجامعة؟", answer: "عادة 45–75 دقيقة حسب عدد الحمامات." },
    ],
    neighbors: ["al-faisaliyyah", "al-rawabi", "as-safa", "al-waziriyah"],
  },
  {
    slug: "al-faisaliyyah",
    archetype: "central-urban",
    character:
      "حي الفيحاء (الفيصلية في البيانات) سكني هادئ؛ فلل وعمائر متوسطة. طلبات كشف بعد تجديد المطابخ وعزل أسطح متوسطة.",
    buildingTypes: ["فلل", "عمائر", "شقق"],
    issues: [
      { title: "مطبخ مجدد", detail: "تسرب وصلة." },
      { title: "سطح", detail: "عزل." },
      { title: "خزان", detail: "صيانة." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "مطبخ وحمام.",
      "سطح.",
      "خزان.",
      "ضغط.",
    ],
    insulationFocus: "عزل مطبخ/حمام في الفيحاء عند التجديد.",
    seasonalNote: "اختبار ضغط بعد السباكة.",
    scenarios: [
      { title: "مطبخ", body: "وصلة مجلى." },
      { title: "سطح", body: "بيتومين." },
    ],
    tips: [
      "اختبار ضغط.",
      "عزل عند التجديد.",
      "فحص سطح.",
      "خزان سنوي.",
      "تقرير فاتورة.",
      "كشف قبل الشراء.",
    ],
    extraFaqs: [
      { question: "الفيحاء vs الفيصلية؟", answer: "نفس الحي في الموقع — slug al-faisaliyyah." },
      { question: "فلل؟", answer: "نعم." },
    ],
    neighbors: ["al-jamaa", "al-rawabi", "al-waziriyah", "as-safa"],
  },
  {
    slug: "al-rawabi",
    archetype: "north-villa",
    character:
      "الروابي شمال جدة؛ فلل وعمائر حديثة بأسطح واسعة. عزل فوم وكشف خزانات علوية من الطلبات الرئيسية.",
    buildingTypes: ["فلل", "فلل دوبلكس", "عمائر"],
    issues: [
      { title: "سطح واسع", detail: "عزل منتهي." },
      { title: "خزان علوي", detail: "تشقق." },
      { title: "حرارة عالية", detail: "عزل حراري." },
      { title: "ري", detail: "حديقة." },
    ],
    inspectionPriorities: [
      "مسح سطح حراري.",
      "خزانات.",
      "ري.",
      "تقرير.",
    ],
    insulationFocus: "فوم للأسطح الكبيرة في الروابي — معيار شائع.",
    seasonalNote: "قبل الصيف والأمطار.",
    scenarios: [
      { title: "فيلا", body: "فوم — خفض حرارة." },
      { title: "خزان", body: "إيبوكسي." },
    ],
    tips: [
      "فوم للسطح.",
      "فحص خزان.",
      "ري عند السفر.",
      "مراقبة فواتير.",
      "كشف استلام.",
      "تقرير بيع.",
    ],
    extraFaqs: [
      { question: "فوم الروابي؟", answer: "مناسب للأسطح الواسعة." },
      { question: "شمال جدة؟", answer: "نعم، أولوية." },
    ],
    neighbors: ["as-safa", "al-jamaa", "al-muntazahat", "al-hamra"],
  },
  {
    slug: "al-waziriyah",
    archetype: "central-urban",
    character:
      "الوزيرية حي سكني مركزي؛ عمائر وشقق متنوعة. تسربات الحمامات والخزانات مع طلب تقارير فنية.",
    buildingTypes: ["عمائر", "شقق", "فلل"],
    issues: [
      { title: "حمام", detail: "وصلات." },
      { title: "خزان", detail: "علوي." },
      { title: "فاتورة", detail: "تقرير." },
      { title: "سطح", detail: "عزل." },
    ],
    inspectionPriorities: [
      "حمام وخزان.",
      "سطح.",
      "عداد.",
      "تقرير.",
    ],
    insulationFocus: "عزل حسب عمر المبنى في الوزيرية.",
    seasonalNote: "كشف مبكر عند رطوبة.",
    scenarios: [
      { title: "تقرير", body: "فاتورة — توثيق." },
      { title: "حمام", body: "عزل فوم." },
    ],
    tips: [
      "تقرير عند النزاع.",
      "عزل حمام.",
      "فحص خزان.",
      "كشف مبكر.",
      "تنسيق عمارة.",
      "اختبار ضغط.",
    ],
    extraFaqs: [
      { question: "تقرير الوزيرية؟", answer: "متاح." },
      { question: "عمائر؟", answer: "نعم." },
    ],
    neighbors: ["al-jamaa", "al-faisaliyyah", "al-sulimaniyah", "al-rehab"],
  },
  {
    slug: "ghulail",
    archetype: "historic",
    character:
      "غليل من الأحياء الجنوبية القديمة؛ كثافة عالية ومبانٍ قديمة. تسربات الخزانات والشبكات المشتركة تحتاج صبرًا ومنهجية.",
    buildingTypes: ["عمائر قديمة", "شقق", "محلات"],
    issues: [
      { title: "شبكة قديمة", detail: "تآكل." },
      { title: "خزان", detail: "أرضي/علوي." },
      { title: "عمارة", detail: "خط مشترك." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "تقييم شبكة.",
      "خزان.",
      "بدروم.",
      "تقرير عمارة.",
    ],
    insulationFocus: "إصلاح ثم عزل عند الترميم في غليل.",
    seasonalNote: "تنسيق إدارة العمارة.",
    scenarios: [
      { title: "عمارة", body: "خط قديم." },
      { title: "خزان", body: "إيبوكسي." },
    ],
    tips: [
      "تنسيق عمارة.",
      "كشف قبل ترميم.",
      "تقرير فاتورة.",
      "فحص بدروم.",
      "إيبوكسي خزان.",
      "لا تكسير عشوائي.",
    ],
    extraFaqs: [
      { question: "غليل جنوب؟", answer: "نعم، تغطية." },
      { question: "عمارات قديمة؟", answer: "خبرة." },
    ],
    neighbors: ["al-kandarah", "al-thaalbah", "al-quzain", "al-nuzlah-al-yamaniyah"],
  },
  {
    slug: "al-quzain",
    archetype: "southern-dense",
    character:
      "القوزين حي جنوبي كثيف؛ عمائر وشقق. تسربات الحمامات والفواتير المرتفعة شائعة. استجابة سريعة.",
    buildingTypes: ["عمائر", "شقق", "محلات"],
    issues: [
      { title: "حمام", detail: "تسرب." },
      { title: "فاتورة", detail: "عمارة." },
      { title: "خزان", detail: "صيانة." },
      { title: "بدروم", detail: "أمطار." },
    ],
    inspectionPriorities: [
      "حمامات.",
      "خزان.",
      "بدروم.",
      "خط عمارة.",
    ],
    insulationFocus: "عزل حمامات وأسطح في القوزين.",
    seasonalNote: "بدروم بعد أمطار.",
    scenarios: [
      { title: "عمارة", body: "فاتورة — خط رئيسي." },
      { title: "حمام", body: "وصلة." },
    ],
    tips: [
      "تنسيق عمارة.",
      "فحص بدروم.",
      "كشف مبكر.",
      "تقرير فاتورة.",
      "عزل عند التجديد.",
      "صيانة خزان.",
    ],
    extraFaqs: [
      { question: "القوزين ضمن النطاق؟", answer: "نعم، جنوب جدة." },
      { question: "عمارة كاملة؟", answer: "بعد المعاينة." },
    ],
    neighbors: ["ghulail", "al-nuzlah-al-sharqiyah", "al-fadilah", "al-harazat"],
  },
  {
    slug: "al-nuzlah-al-yamaniyah",
    archetype: "historic",
    character:
      "النزلة اليمانية من الأحياء التاريخية الجنوبية؛ مباني قديمة وشبكات متقادمة. الكشف المنهجي يمنع تكسيرًا واسعًا.",
    buildingTypes: ["مباني قديمة", "شقق", "محلات"],
    issues: [
      { title: "مواسير قديمة", detail: "تآكل." },
      { title: "تسرب خفي", detail: "فاتورة." },
      { title: "خزان", detail: "أرضي." },
      { title: "ترميم", detail: "بدون كشف." },
    ],
    inspectionPriorities: [
      "فحص حراري.",
      "خزان أرضي.",
      "تقييم مواسير.",
      "تقرير.",
    ],
    insulationFocus: "عزل عند الترميم الكامل في النزلة اليمانية.",
    seasonalNote: "قبل ترميم — كشف.",
    scenarios: [
      { title: "تسرب خفي", body: "كشف حراري." },
      { title: "ترميم", body: "قبل بلاط." },
    ],
    tips: [
      "كشف قبل ترميم.",
      "فحص خزان أرضي.",
      "لا تكسير عشوائي.",
      "تقرير فاتورة.",
      "استبدال تالف.",
      "توثيق.",
    ],
    extraFaqs: [
      { question: "حي تاريخي؟", answer: "نعم، كشف بحذر." },
      { question: "تقرير؟", answer: "متاح." },
    ],
    neighbors: ["al-nuzlah-al-sharqiyah", "ghulail", "al-thaalbah", "al-kandarah"],
  },
  {
    slug: "al-nuzlah-al-sharqiyah",
    archetype: "historic",
    character:
      "النزلة الشرقية حي قديم كثيف جنوبًا؛ تسربات بين الطوابق وخطوط العمارات المشتركة. يحتاج تنسيقًا بين السكان.",
    buildingTypes: ["عمائر قديمة", "شقق", "محلات"],
    issues: [
      { title: "بين طوابق", detail: "حمام." },
      { title: "خط مشترك", detail: "عمارة." },
      { title: "خزان", detail: "قديم." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "حمام علوي.",
      "خط عمارة.",
      "خزان.",
      "تنسيق.",
    ],
    insulationFocus: "عزل حمام عند الترميم في النزلة الشرقية.",
    seasonalNote: "تدخل سريع.",
    scenarios: [
      { title: "بين طوابق", body: "حمام علوي." },
      { title: "عمارة", body: "خط مشترك." },
    ],
    tips: [
      "تواصل علوي.",
      "تنسيق عمارة.",
      "كشف مبكر.",
      "تقرير فاتورة.",
      "عزل عند التجديد.",
      "فحص خزان.",
    ],
    extraFaqs: [
      { question: "شرقية vs يمانية؟", answer: "صفحتان مستقلتان." },
      { question: "تسرب جار؟", answer: "فحص موضوعي." },
    ],
    neighbors: ["al-nuzlah-al-yamaniyah", "al-quzain", "ghulail", "al-harazat"],
  },
  {
    slug: "as-safa-2",
    archetype: "north-villa",
    character:
      "الصفا 2 امتداد لحي الصفا الشمالي؛ فلل وعمائر حديثة. عزل فوم وكشف خزانات — نفس معايير الصفا مع كثافة أقل نسبيًا.",
    buildingTypes: ["فلل", "عمائر حديثة", "شقق"],
    issues: [
      { title: "سطح واسع", detail: "فوم." },
      { title: "خزان", detail: "علوي." },
      { title: "فاتورة", detail: "فيلا." },
      { title: "حمام مجدد", detail: "وصلة." },
    ],
    inspectionPriorities: [
      "سطح حراري.",
      "خزان.",
      "حمام.",
      "ضغط.",
    ],
    insulationFocus: "فوم للأسطح في الصفا 2.",
    seasonalNote: "فحص استلام للفلل الجديدة.",
    scenarios: [
      { title: "فيلا جديدة", body: "فوم سطح." },
      { title: "حمام", body: "اختبار ضغط." },
    ],
    tips: [
      "فوم سطح.",
      "فحص استلام.",
      "اختبار ضغط.",
      "خزان سنوي.",
      "تقرير بيع.",
      "لا تخلط مع الصفا 1 فقط.",
    ],
    extraFaqs: [
      { question: "الفرق عن الصفا؟", answer: "منطقة أحدث — نفس الجودة." },
      { question: "فوم؟", answer: "نعم." },
    ],
    neighbors: ["as-safa", "al-rawabi", "al-zahraa", "al-hamra"],
  },
  {
    slug: "mushrifah",
    archetype: "central-urban",
    character:
      "مشرفة حي سكني معروف؛ فلل وعمائر. يكثر طلب عزل الأسطح والخزانات العلوية بعد الأمطار. صيانة الميزانين مهمة.",
    buildingTypes: ["فلل", "عمائر", "شقق"],
    issues: [
      { title: "سطح بعد أمطار", detail: "تسرب سقف." },
      { title: "خزان علوي", detail: "تشقق." },
      { title: "ميزانين", detail: "مسدود." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "سطح وميزانين.",
      "خزان.",
      "مصارف أمطار.",
      "حمام.",
    ],
    insulationFocus: "بيتومين أو فوم لأسطح مشرفة حسب المساحة.",
    seasonalNote: "قبل الأمطار — فحص ميزانين.",
    scenarios: [
      { title: "بعد أمطار", body: "ميزانين — عزل." },
      { title: "خزان", body: "إصلاح." },
    ],
    tips: [
      "فحص ميزانين قبل الشتاء.",
      "عزل سطح.",
      "صيانة خزان.",
      "تنظيف مصارف.",
      "كشف عند بقعة سقف.",
      "تقرير فاتورة.",
    ],
    extraFaqs: [
      { question: "مشرفة — أمطار؟", answer: "نعم، أولوية ميزانين." },
      { question: "فلل؟", answer: "نعم." },
    ],
    neighbors: ["al-zahraa", "al-nuzhah", "al-rehab", "al-warood"],
  },
  {
    slug: "bani-malik",
    archetype: "southern-dense",
    character:
      "بني مالك حي جنوبي سكني؛ عمائر وشقق بكثافة متوسطة. تسربات الحمامات والعداد الليلي شائعة.",
    buildingTypes: ["عمائر", "شقق", "فلل صغيرة"],
    issues: [
      { title: "عداد ليلًا", detail: "صمام." },
      { title: "حمام", detail: "وصلات." },
      { title: "خزان", detail: "علوي." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "اختبار عداد ليلي.",
      "حمامات.",
      "خزان.",
      "تقرير.",
    ],
    insulationFocus: "عزل حمام عند التسرب المؤكد في بني مالك.",
    seasonalNote: "فحص صمامات المراحيل.",
    scenarios: [
      { title: "عداد ليلًا", body: "صمام دش." },
      { title: "حمام", body: "وصلة." },
    ],
    tips: [
      "قراءة عداد ليلًا.",
      "فحص مراحيل.",
      "كشف مبكر.",
      "تنسيق عمارة.",
      "تقرير فاتورة.",
      "عزل عند التجديد.",
    ],
    extraFaqs: [
      { question: "بني مالك جنوب؟", answer: "نعم." },
      { question: "شقق؟", answer: "نعم." },
    ],
    neighbors: ["al-fadilah", "al-harazat", "al-aziziyah", "madinat-al-fahd"],
  },
  {
    slug: "al-warood",
    archetype: "suburban-new",
    character:
      "الورود حي سكني منظم؛ مجمعات وعمائر أحدث. عزل عند الاستلام وكشف دوري للخزانات.",
    buildingTypes: ["مجمعات", "عمائر", "شقق"],
    issues: [
      { title: "استلام", detail: "عزل ناقص." },
      { title: "خزان", detail: "جديد." },
      { title: "حمامات", detail: "متعددة." },
      { title: "فاتورة", detail: "عالية." },
    ],
    inspectionPriorities: [
      "فحص استلام.",
      "خزان.",
      "سطح.",
      "ضغط.",
    ],
    insulationFocus: "فوم للأسطح الجديدة في الورود.",
    seasonalNote: "فحص أول 3 سنوات.",
    scenarios: [
      { title: "استلام", body: "تقرير عزل." },
      { title: "مجمع", body: "خزان مشترك." },
    ],
    tips: [
      "فحص استلام.",
      "فوم سطح.",
      "اختبار ضغط.",
      "توثيق ضمان.",
      "كشف سنوي.",
      "تنسيق إدارة.",
    ],
    extraFaqs: [
      { question: "مجمعات الورود؟", answer: "نعم." },
      { question: "استلام؟", answer: "فحص شامل." },
    ],
    neighbors: ["al-rehab", "al-sulimaniyah", "mushrifah", "al-naseem"],
  },
  {
    slug: "madinat-al-fahd",
    archetype: "southern-dense",
    character:
      "مدينة الفهد حي جنوبي واسع؛ فلل وعمائر. تسربات الأسطح والري الخارجي من البلاغات الشائعة.",
    buildingTypes: ["فلل", "عمائر", "شقق"],
    issues: [
      { title: "ري خارجي", detail: "فاتورة." },
      { title: "سطح", detail: "أمطار." },
      { title: "خزان", detail: "صيانة." },
      { title: "حمام", detail: "تسرب." },
    ],
    inspectionPriorities: [
      "ري وسطح.",
      "خزان.",
      "حمام.",
      "عداد.",
    ],
    insulationFocus: "عزل أسطح وخزانات في مدينة الفهد.",
    seasonalNote: "إغلاق ري عند السفر.",
    scenarios: [
      { title: "ري", body: "صمام خارجي." },
      { title: "سطح", body: "عزل بعد أمطار." },
    ],
    tips: [
      "إغلاق ري سفر.",
      "فحص سطح.",
      "صيانة خزان.",
      "كشف مبكر.",
      "تقرير فاتورة.",
      "عزل سطح.",
    ],
    extraFaqs: [
      { question: "مدينة الفهد — مساحة؟", answer: "فلل وعمائر — معاينة ميدانية." },
      { question: "ري؟", answer: "نفحص خطوط الري." },
    ],
    neighbors: ["bani-malik", "al-fadilah", "al-harazat", "al-ajawid"],
  },
  {
    slug: "obhur-al-janubiyah",
    archetype: "coastal",
    character:
      "أبحر الجنوبية قريبة من الساحل؛ فلل وعمائر. الملوحة تؤثر على الخزانات وخطوط الري. فحص شامل للشبكة الداخلية والخارجية.",
    buildingTypes: ["فلل ساحلية", "عمائر", "استراحات"],
    issues: [
      { title: "ملوحة", detail: "تآكل وصلات." },
      { title: "ري وحديقة", detail: "فاتورة." },
      { title: "خزان", detail: "تشقق." },
      { title: "سطح", detail: "عزل." },
    ],
    inspectionPriorities: [
      "خزان وملوحة.",
      "ري خارجي.",
      "سطح.",
      "شبكة داخلية.",
    ],
    insulationFocus: "مواد مقاومة للملوحة في أبحر الجنوبية.",
    seasonalNote: "رياح ساحلية — فحص سطح.",
    scenarios: [
      { title: "ري", body: "فاتورة — خط حديقة." },
      { title: "خزان", body: "إيبوكسي." },
    ],
    tips: [
      "مواد ملوحة.",
      "فحص ري.",
      "إيبوكسي خزان.",
      "عزل سطح.",
      "تقرير فاتورة.",
      "كشف فيلا بحرية.",
    ],
    extraFaqs: [
      { question: "جنوبية vs شمالية أبحر؟", answer: "صفحتان منفصلتان." },
      { question: "ملوحة؟", answer: "نراعيها في المواد." },
    ],
    neighbors: ["obhur-al-shamaliyah", "abhur", "al-amwaj", "al-shatie"],
  },
  {
    slug: "obhur-al-shamaliyah",
    archetype: "north-villa",
    character:
      "أبحر الشمالية من أكثر مناطق جدة طلبًا لفلل واسعة وعزل فوم. الحرارة والرياح تجهد العزل القديم. خزانات علوية ومسابح.",
    buildingTypes: ["فلل فاخرة", "قصور صغيرة", "عمائر"],
    issues: [
      { title: "سطح واسع جدًا", detail: "عزل فوم." },
      { title: "خزان علوي كبير", detail: "تشقق." },
      { title: "مسابح وري", detail: "استهلاك." },
      { title: "حرارة", detail: "عزل حراري." },
    ],
    inspectionPriorities: [
      "مسح سطح كامل.",
      "خزانات متعددة.",
      "مسابح وري.",
      "تقرير مفصل.",
    ],
    insulationFocus: "فوم متكامل لأسطح أبحر الشمالية — معيار المنطقة.",
    seasonalNote: "معاينة ميدانية قبل تسعير المتر.",
    scenarios: [
      { title: "فيلا كبيرة", body: "فوم — خفض حرارة وتسرب." },
      { title: "خزان", body: "إيبوكسي + صيانة." },
    ],
    tips: [
      "معاينة قبل عرض سعر.",
      "فوم للأسطح الكبيرة.",
      "صيانة مسبح.",
      "فحص ري.",
      "خزان نصف سنوي.",
      "تقرير قبل بيع.",
    ],
    extraFaqs: [
      { question: "أبحر الشمالية — أولوية؟", answer: "نعم، زيارات منتظمة." },
      { question: "تسعير فوم؟", answer: "بعد المعاينة." },
    ],
    neighbors: ["obhur-al-janubiyah", "al-yaqoot", "al-lulu", "abhur"],
  },
  {
    slug: "al-yaqoot",
    archetype: "north-villa",
    character:
      "الياقوت من أحياء أبحر السكنية الراقية؛ فلل حديثة. عزل فوم وكشف خزانات — نفس بيئة أبحر الشمالية.",
    buildingTypes: ["فلل", "فلل دوبلكس"],
    issues: [
      { title: "سطح", detail: "فوم." },
      { title: "خزان", detail: "علوي." },
      { title: "ري", detail: "حديقة." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "سطح.",
      "خزان.",
      "ري.",
      "ضغط.",
    ],
    insulationFocus: "فوم للأسطح في الياقوت.",
    seasonalNote: "فحص قبل الصيف.",
    scenarios: [
      { title: "فيلا", body: "فوم." },
      { title: "ري", body: "صمام." },
    ],
    tips: [
      "فوم سطح.",
      "فحص ري.",
      "خزان دوري.",
      "معاينة قبل عزل.",
      "تقرير بيع.",
      "كشف استلام.",
    ],
    extraFaqs: [
      { question: "الياقوت أبحر؟", answer: "نعم، شمال أبحر." },
      { question: "فوم؟", answer: "مناسب." },
    ],
    neighbors: ["al-lulu", "al-kawthar", "obhur-al-shamaliyah", "al-amwaj"],
  },
  {
    slug: "al-lulu",
    archetype: "north-villa",
    character:
      "اللؤلؤ حي فلل أبحر؛ أسطح واسعة وخزانات علوية. عزل حراري ومائي متكامل مطلوب.",
    buildingTypes: ["فلل", "قصور"],
    issues: [
      { title: "عزل منتهي", detail: "حرارة وتسرب." },
      { title: "خزان", detail: "كبير." },
      { title: "مسابح", detail: "صيانة." },
      { title: "فاتورة", detail: "عالية." },
    ],
    inspectionPriorities: [
      "سطح حراري.",
      "خزان.",
      "مسابح.",
      "ري.",
    ],
    insulationFocus: "فوم اللؤلؤ — استثمار طويل.",
    seasonalNote: "قبل الصيف والأمطار.",
    scenarios: [
      { title: "فيلا", body: "فوم شامل." },
      { title: "مسابح", body: "تسرب نظام." },
    ],
    tips: [
      "فوم شامل.",
      "صيانة مسبح.",
      "خزان نصف سنوي.",
      "فحص ري.",
      "معاينة مسبقة.",
      "تقرير بيع.",
    ],
    extraFaqs: [
      { question: "اللؤلؤ فلل فقط؟", answer: "غالبًا فلل واسعة." },
      { question: "مسابح؟", answer: "نفحص أنظمة المياه المرتبطة." },
    ],
    neighbors: ["al-yaqoot", "al-kawthar", "al-amwaj", "obhur-al-shamaliyah"],
  },
  {
    slug: "al-kawthar",
    archetype: "north-villa",
    character:
      "الكوثر حي أبحر سكني؛ فلل بمساحات جيدة. تسربات الخزان العلوي بعد الحر شائعة.",
    buildingTypes: ["فلل", "عمائر قليلة"],
    issues: [
      { title: "خزان حر", detail: "تشقق." },
      { title: "سطح", detail: "عزل." },
      { title: "ري", detail: "حديقة." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "خزان أولًا.",
      "سطح.",
      "ري.",
      "حمام.",
    ],
    insulationFocus: "إيبوكسي خزان + فوم سطح في الكوثر.",
    seasonalNote: "فحص خزان قبل الصيف.",
    scenarios: [
      { title: "خزان", body: "إيبوكسي." },
      { title: "سطح", body: "فوم." },
    ],
    tips: [
      "فحص خزان قبل حر.",
      "فوم سطح.",
      "إيبوكسي عند تشقق.",
      "ري سفر.",
      "تقرير فاتورة.",
      "معاينة عزل.",
    ],
    extraFaqs: [
      { question: "الكوثر أبحر؟", answer: "نعم." },
      { question: "إيبوكسي خزان؟", answer: "نعم." },
    ],
    neighbors: ["al-lulu", "al-yaqoot", "al-amwaj", "taibah"],
  },
  {
    slug: "al-amwaj",
    archetype: "coastal",
    character:
      "الأمواج منطقة ساحلية راقية؛ أبراج وفلل. الملوحة والرياح تؤثر على العزل. كشف وعزل بمعايير عالية.",
    buildingTypes: ["أبراج", "فلل", "شقق فاخرة"],
    issues: [
      { title: "واجهات بحرية", detail: "رطوبة." },
      { title: "خزان علوي", detail: "أبراج." },
      { title: "عزل واجهة", detail: "ملوحة." },
      { title: "فاتورة", detail: "شقة/فيلا." },
    ],
    inspectionPriorities: [
      "واجهة وخزان.",
      "سطح مشترك أحيانًا.",
      "فحص حراري.",
      "تقرير.",
    ],
    insulationFocus: "مواد مقاومة للملوحة في الأمواج.",
    seasonalNote: "أبراج — تنسيق إدارة.",
    scenarios: [
      { title: "شقة بحرية", body: "رطوبة واجهة — تصريف." },
      { title: "برج", body: "خزان علوي مشترك." },
    ],
    tips: [
      "تنسيق إدارة برج.",
      "مواد ملوحة.",
      "فحص واجهة.",
      "خزان دوري.",
      "تقرير فاتورة.",
      "كشف قبل شراء.",
    ],
    extraFaqs: [
      { question: "أبراج الأمواج؟", answer: "نعم، مع إدارة." },
      { question: "ملوحة؟", answer: "أولوية في المواد." },
    ],
    neighbors: ["al-lulu", "al-yaqoot", "obhur-al-janubiyah", "abhur"],
  },
  {
    slug: "taibah",
    archetype: "suburban-new",
    character:
      "طيبة حي سكني حديث نسبيًا؛ مجمعات وعمائر. فحص استلام وعزل للأسطح الجديدة.",
    buildingTypes: ["مجمعات", "فلل", "عمائر"],
    issues: [
      { title: "استلام", detail: "عزل." },
      { title: "خزان", detail: "جديد." },
      { title: "حمام", detail: "تسرب." },
      { title: "فاتورة", detail: "عالية." },
    ],
    inspectionPriorities: [
      "استلام.",
      "سطح.",
      "خزان.",
      "ضغط.",
    ],
    insulationFocus: "فوم لأسطح طيبة الجديدة.",
    seasonalNote: "فحص 3 سنوات أولى.",
    scenarios: [
      { title: "استلام", body: "تقرير عزل." },
      { title: "حمام", body: "ضغط." },
    ],
    tips: [
      "فحص استلام.",
      "فوم.",
      "اختبار ضغط.",
      "ضمان مطور.",
      "كشف سنوي.",
      "تنسيق إدارة.",
    ],
    extraFaqs: [
      { question: "طيبة جديدة؟", answer: "فحص استلام مناسب." },
      { question: "مجمعات؟", answer: "نعم." },
    ],
    neighbors: ["al-kawthar", "al-muntazahat", "al-ajawid", "al-naseem"],
  },
  {
    slug: "al-muntazahat",
    archetype: "north-villa",
    character:
      "المنتزهات شمال جدة؛ فلل واسعة وأسطح كبيرة. عزل فوم وكشف شامل قبل وبعد الأمطار.",
    buildingTypes: ["فلل", "عمائر"],
    issues: [
      { title: "سطح كبير", detail: "فوم." },
      { title: "خزان", detail: "علوي." },
      { title: "أمطار", detail: "تسرب." },
      { title: "حرارة", detail: "كهرباء." },
    ],
    inspectionPriorities: [
      "مسح سطح.",
      "خزان.",
      "مصارف.",
      "تقرير.",
    ],
    insulationFocus: "فوم المنتزهات — معيار الفلل الواسعة.",
    seasonalNote: "قبل الأمطار.",
    scenarios: [
      { title: "فيلا", body: "فوم + أمطار." },
      { title: "مصارف", body: "تنظيف وعزل." },
    ],
    tips: [
      "فوم سطح.",
      "مصارف قبل شتاء.",
      "خزان دوري.",
      "معاينة مسبقة.",
      "تقرير بيع.",
      "مراقبة كهرباء.",
    ],
    extraFaqs: [
      { question: "المنتزهات شمال؟", answer: "نعم." },
      { question: "أسطح واسعة؟", answer: "معاينة إلزامية." },
    ],
    neighbors: ["al-rawabi", "as-safa", "taibah", "al-naseem"],
  },
  {
    slug: "al-ajawid",
    archetype: "southern-dense",
    character:
      "الأجاويد حي جنوبي؛ عمائر وشقق. تسربات الحمامات والبدروم بعد الأمطار.",
    buildingTypes: ["عمائر", "شقق", "فلل"],
    issues: [
      { title: "بدروم", detail: "أمطار." },
      { title: "حمام", detail: "تسرب." },
      { title: "خزان", detail: "علوي." },
      { title: "فاتورة", detail: "عمارة." },
    ],
    inspectionPriorities: [
      "بدروم.",
      "حمام.",
      "خزان.",
      "خط عمارة.",
    ],
    insulationFocus: "عزل أسطح وحمامات الأجاويد.",
    seasonalNote: "بدروم بعد أمطار.",
    scenarios: [
      { title: "بدروم", body: "خط — ليس أمطار فقط." },
      { title: "عمارة", body: "فاتورة." },
    ],
    tips: [
      "فحص بدروم.",
      "تنسيق عمارة.",
      "كشف مبكر.",
      "تقرير فاتورة.",
      "عزل سطح.",
      "صيانة خزان.",
    ],
    extraFaqs: [
      { question: "الأجاويد جنوب؟", answer: "نعم." },
      { question: "بدروم؟", answer: "نفحصه أولًا." },
    ],
    neighbors: ["madinat-al-fahd", "al-harazat", "taibah", "al-fadilah"],
  },
  {
    slug: "al-harazat",
    archetype: "southern-dense",
    character:
      "الحرازات حي جنوبي كثيف؛ عمائر وشقق. خطوط مشتركة وفواتير مرتفعة تحتاج تقريرًا واضحًا.",
    buildingTypes: ["عمائر", "شقق", "محلات"],
    issues: [
      { title: "خط مشترك", detail: "عمارة." },
      { title: "فاتورة", detail: "مرتفعة." },
      { title: "حمام", detail: "تسرب." },
      { title: "خزان", detail: "صيانة." },
    ],
    inspectionPriorities: [
      "خط عمارة.",
      "حمامات.",
      "خزان.",
      "تقرير.",
    ],
    insulationFocus: "عزل عند الترميم في الحرازات.",
    seasonalNote: "تنسيق إدارة.",
    scenarios: [
      { title: "عمارة", body: "خط رئيسي." },
      { title: "محل", body: "مشترك." },
    ],
    tips: [
      "تنسيق عمارة.",
      "تقرير فاتورة.",
      "كشف مبكر.",
      "فحص بدروم.",
      "عزل عند التجديد.",
      "لا إصلاح دون مصدر.",
    ],
    extraFaqs: [
      { question: "الحرازات كثيف؟", answer: "نعم، تنسيق مهم." },
      { question: "تقرير؟", answer: "متاح." },
    ],
    neighbors: ["al-quzain", "al-fadilah", "bani-malik", "al-ajawid"],
  },
  {
    slug: "al-fadilah",
    archetype: "southern-dense",
    character:
      "الفضيلة حي جنوبي؛ عمائر وشقق متوسطة العمر. كشف تسربات وعزل بأسعار معقولة بعد معاينة.",
    buildingTypes: ["عمائر", "شقق", "فلل صغيرة"],
    issues: [
      { title: "حمام", detail: "وصلات." },
      { title: "سطح", detail: "عزل قديم." },
      { title: "خزان", detail: "علوي." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "حمام.",
      "سطح.",
      "خزان.",
      "عداد.",
    ],
    insulationFocus: "بيتومين أو فوم حسب الميزانية في الفضيلة.",
    seasonalNote: "معاينة قبل التسعير.",
    scenarios: [
      { title: "شقة", body: "حمام — عزل." },
      { title: "سطح", body: "بيتومين." },
    ],
    tips: [
      "معاينة مجانية للتسعير.",
      "كشف مبكر.",
      "عزل عند التجديد.",
      "تقرير فاتورة.",
      "صيانة خزان.",
      "تنسيق عمارة.",
    ],
    extraFaqs: [
      { question: "الفضيلة — تسعير؟", answer: "بعد المعاينة." },
      { question: "شقق؟", answer: "نعم." },
    ],
    neighbors: ["al-aziziyah", "bani-malik", "al-harazat", "al-quzain"],
  },
  {
    slug: "al-manar",
    archetype: "suburban-new",
    character:
      "حي المنار من الأحياء السكنية الحديثة في جنوب شرق جدة؛ عمائر ومجمعات منظمة بشوارع واسعة. يكثر طلب كشف التسربات بعد استلام الوحدات الجديدة وعزل الأسطح قبل أول موسم أمطار.",
    buildingTypes: ["مجمعات سكنية", "عمائر حديثة", "فلل صغيرة"],
    issues: [
      { title: "عيوب استلام", detail: "عزل ناقص أو وصلات سباكة غير مختبرة بالضغط." },
      { title: "خزان علوي جديد متشقق", detail: "تشققات دقيقة من النقل أو التركيب." },
      { title: "فاتورة مرتفعة بعد السكن", detail: "خلال أول 3 أشهر — غالبًا تسرب خفي." },
      { title: "سطح مجمع سكني", detail: "مسؤولية مشتركة بين الوحدات." },
    ],
    inspectionPriorities: [
      "فحص استلام شامل للشقة أو الفيلا.",
      "اختبار ضغط لكل الحمامات.",
      "مراجعة عزل السطح المشترك مع إدارة المجمع.",
      "توثيق للضمان والمطور.",
    ],
    insulationFocus:
      "في المنار ننصح بفوم للأسطح الفردية الكبيرة وبيتومين للمساحات المتوسطة — حسب تقرير المعاينة.",
    seasonalNote: "قبل أول أمطار بعد الاستلام — فحص سطح وخزان إلزامي.",
    scenarios: [
      { title: "شقة مستلمة — فاتورة عالية", body: "تسرب من صمام دش ضيف؛ إصلاح في ساعة." },
      { title: "مجمع — سطح مشترك", body: "تنسيق مع الإدارة لعزل القسم المتضرر." },
    ],
    tips: [
      "فحص استلام قبل التوقيع النهائي.",
      "اختبار ضغط لكل حمام.",
      "طلب تقرير عزل من المطور.",
      "مراقبة العداد أول شهر.",
      "تنسيق مع إدارة المجمع للأسطح.",
      "فوم أو بيتومين بعد معاينة.",
    ],
    extraFaqs: [
      { question: "هل حي المنار من الأحياء الجديدة؟", answer: "نعم، نركز على فحص الاستلام والعزل للمباني الحديثة." },
      { question: "مجمعات المنار؟", answer: "نعمل مع إدارات المجمعات للخزانات والأسطح المشتركة." },
    ],
    neighbors: ["al-sanabel", "al-marwah", "al-naseem", "al-tawfiq"],
  },
  {
    slug: "al-sanabel",
    archetype: "suburban-new",
    character:
      "السنابل حي سكني حديث مجاور للمنار؛ مجمعات وعمائر. طلبات عزل وكشف استلام متكررة.",
    buildingTypes: ["مجمعات", "عمائر", "شقق"],
    issues: [
      { title: "استلام", detail: "عزل." },
      { title: "خزان", detail: "جديد." },
      { title: "ضغط", detail: "لم يُختبر." },
      { title: "فاتورة", detail: "أول شهر." },
    ],
    inspectionPriorities: [
      "استلام.",
      "ضغط.",
      "خزان.",
      "سطح.",
    ],
    insulationFocus: "فوم للأسطح الجديدة في السنابل.",
    seasonalNote: "فحص قبل أول أمطار.",
    scenarios: [
      { title: "استلام", body: "تقرير عزل." },
      { title: "ضغط", body: "وصلة حمام." },
    ],
    tips: [
      "فحص استلام.",
      "اختبار ضغط.",
      "فوم سطح.",
      "مراقبة عداد.",
      "تنسيق إدارة.",
      "ضمان مطور.",
    ],
    extraFaqs: [
      { question: "السنابل قرب المنار؟", answer: "نعم، نفس فريق المنطقة." },
      { question: "استلام؟", answer: "فحص شامل." },
    ],
    neighbors: ["al-manar", "al-marwah", "al-naseem", "al-tawfiq"],
  },
  {
    slug: "al-marwah",
    archetype: "suburban-new",
    character:
      "المروة حي سكني حديث جنوب شرق؛ شقق ومجمعات. تسربات ما بعد الاستلام وعزل خزانات.",
    buildingTypes: ["مجمعات", "شقق", "عمائر"],
    issues: [
      { title: "بعد استلام", detail: "تسرب." },
      { title: "خزان", detail: "علوي." },
      { title: "حمام", detail: "وصلة." },
      { title: "سطح", detail: "عزل." },
    ],
    inspectionPriorities: [
      "استلام/ضغط.",
      "خزان.",
      "حمام.",
      "سطح.",
    ],
    insulationFocus: "عزل خزان وحمام في المروة.",
    seasonalNote: "أول 6 أشهر — مراقبة.",
    scenarios: [
      { title: "شقة جديدة", body: "وصلة — إصلاح." },
      { title: "خزان", body: "إيبوكسي." },
    ],
    tips: [
      "مراقبة أول 6 أشهر.",
      "اختبار ضغط.",
      "فحص خزان.",
      "عزل حمام.",
      "تقرير مطور.",
      "كشف عند رطوبة.",
    ],
    extraFaqs: [
      { question: "المروة جديدة؟", answer: "نعم." },
      { question: "إيبوكسي؟", answer: "حسب الخزان." },
    ],
    neighbors: ["al-manar", "al-sanabel", "al-naseem", "al-rawdah-2"],
  },
  {
    slug: "al-naseem",
    archetype: "suburban-new",
    character:
      "النسيم حي سكني واسع جنوب شرق؛ فلل ومجمعات. عزل أسطح وكشف خزانات بعد الأمطار.",
    buildingTypes: ["فلل", "مجمعات", "عمائر"],
    issues: [
      { title: "سطح", detail: "أمطار." },
      { title: "خزان", detail: "علوي." },
      { title: "ري", detail: "حديقة." },
      { title: "فاتورة", detail: "مرتفعة." },
    ],
    inspectionPriorities: [
      "سطح.",
      "خزان.",
      "ري.",
      "حمام.",
    ],
    insulationFocus: "فوم أو بيتومين للنسيم حسب المساحة.",
    seasonalNote: "قبل الأمطار.",
    scenarios: [
      { title: "فيلا", body: "سطح — عزل." },
      { title: "ري", body: "صمام." },
    ],
    tips: [
      "فحص قبل أمطار.",
      "عزل سطح.",
      "ري سفر.",
      "خزان دوري.",
      "تقرير فاتورة.",
      "كشف استلام.",
    ],
    extraFaqs: [
      { question: "النسيم واسع؟", answer: "معاينة ميدانية." },
      { question: "فلل؟", answer: "نعم." },
    ],
    neighbors: ["al-manar", "taibah", "al-warood", "al-tawfiq"],
  },
  {
    slug: "al-tawfiq",
    archetype: "suburban-new",
    character:
      "التوفيق حي سكني منظم؛ عمائر وشقق حديثة. كشف دوري للخزانات واختبار ضغط بعد السباكة.",
    buildingTypes: ["عمائر", "شقق", "مجمعات"],
    issues: [
      { title: "سباكة حديثة", detail: "وصلة." },
      { title: "خزان", detail: "صيانة." },
      { title: "فاتورة", detail: "مرتفعة." },
      { title: "سطح", detail: "عزل." },
    ],
    inspectionPriorities: [
      "ضغط.",
      "خزان.",
      "سطح.",
      "عداد.",
    ],
    insulationFocus: "عزل عند التجديد في التوفيق.",
    seasonalNote: "اختبار ضغط بعد أي تركيب.",
    scenarios: [
      { title: "بعد سباكة", body: "ضغط — تسرب." },
      { title: "خزان", body: "صيانة." },
    ],
    tips: [
      "ضغط بعد سباكة.",
      "صيانة خزان.",
      "كشف مبكر.",
      "عزل سطح.",
      "تقرير فاتورة.",
      "تنسيق عمارة.",
    ],
    extraFaqs: [
      { question: "التوفيق — ضغط؟", answer: "جزء من الخدمة." },
      { question: "عمائر؟", answer: "نعم." },
    ],
    neighbors: ["al-manar", "al-sanabel", "al-naseem", "al-rawdah-2"],
  },
  {
    slug: "al-rawdah-2",
    archetype: "central-urban",
    character:
      "الروضة 2 امتداد لحي الروضة؛ عمائر وشقق أحدث نسبيًا. تسربات الحمامات والمطابخ مع طلب تقارير — يختلف عن الروضة القديمة في عمر الشبكة.",
    buildingTypes: ["عمائر", "شقق", "فلل"],
    issues: [
      { title: "مطبخ/حمام", detail: "وصلات." },
      { title: "خزان علوي", detail: "صيانة." },
      { title: "فاتورة", detail: "تقرير." },
      { title: "بعد تجديد", detail: "تسرب." },
    ],
    inspectionPriorities: [
      "حمام ومطبخ.",
      "خزان.",
      "ضغط بعد تجديد.",
      "تقرير.",
    ],
    insulationFocus: "عزل حمام في الروضة 2 عند التجديد.",
    seasonalNote: "لا تخلط مع الروضة القديمة — شبكة أحدث.",
    scenarios: [
      { title: "مطبخ مجدد", body: "وصلة." },
      { title: "تقرير فاتورة", body: "توثيق." },
    ],
    tips: [
      "اختبار ضغط بعد تجديد.",
      "تقرير عند النزاع.",
      "فحص خزان.",
      "عزل حمام.",
      "كشف قبل إيجار.",
      "مراقبة عداد.",
    ],
    extraFaqs: [
      { question: "الروضة 2 vs الروضة؟", answer: "صفحتان — عمر مباني مختلف." },
      { question: "تقرير؟", answer: "متاح." },
    ],
    neighbors: ["ar-rawdah", "al-marwah", "al-tawfiq", "al-salamah"],
  },
];
